export enum EnvVariables {
  /* DATABASE VARIABLES */
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  JWT_SECRET = 'JWT_SECRET',
  DIAS_PROMOCION_JSON_PATH_WIN = 'DIAS_PROMOCION_JSON_PATH_WIN',
  DIAS_PROMOCION_JSON_PATH_LINUX = 'DIAS_PROMOCION_JSON_PATH_LINU',

  /* APP VARIABLES */
  APPLICATION_PORT = 'APPLICATION_PORT',
  APPLICATION_CONTEXT_PATH = 'APPLICATION_CONTEXT_PATH',
}
